### ISSUE TITLE
Error: Input-gain is out of bounds (-10 <= t <= 30) [dB]

### ISSUE THREAD

**Issue by felysu** [ElizabethHarmon/ebu-norm#53]
Hello! First of all, thank you very much for your work on this piece of software.
I was trying to use it today with some VERY loud music and if I set the LUFS target to -23 (so, default), I get this error:
`Error: Input-gain is out of bounds (-10 <= t <= 30) [dB].

./testin.flac
-16.7 dB of gain applied...

Skipped items: 0
`
The negative gain is NOT applied and the item is indeed skipped (nothing coming out in the output folder). 
I'm pretty ignorant with audio, is what I'm trying to do impossible? Thank you in advance!

**Comment by ElizabethHarmon** [comment]
sound-gambit (the program I use behind the scenes) has a limit between -10 and +30dB as stated in its help file. There's not much I can do unfortunately.
